apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tbgroup

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- api-deployment.yaml
- web-deployment.yaml
- admin-deployment.yaml
- ingress.yaml
- hpa.yaml

commonLabels:
  app: tbgroup
  environment: production

commonAnnotations:
  contact: "admin@tbgroup.kz"
  version: "v2.0.0"
